#!/usr/bin/env python3

# Generate usys.S, the stubs for syscalls.

def main():
    print("# generated by usys.py - do not edit")
    print("#include \"sysdef.h\"")
    print(".section .text")
    def entry(name):
        print(f".global __{name}__")
        print(f"__{name}__:")
        print(f" li a7, SYS_{name}")
        print(" ecall")
        print(" ret")

    syscalls = [
        "fork", "exit", "waitpid", "pipe", "read", "write", "close", "kill", "exec",
        "open", "mknod", "unlink", "fstat", "link", "mkdir", "chdir", "dup",
        "getpid", "sbrk", "sleep", "uptime", "sti", "cli", "yield", "gettime", 
        "get_free_page_size", "get_slab_allocated_size", "clone", "exit_thread", "mmap", "munmap", "shmem",
        "sem_init", "sem_post", "sem_wait", "sem_free", "sem_get_value", "event_send", "event_recv",
        "mbox_init", "mbox_send", "mbox_recv", "mbox_free", "mbox_info", "set_sigaction", "send_signal", "sigreturn",
        "setpriority", "getpriority", "get_proc_runticks", "set_proc_cpu"
    ]

    for syscall in syscalls:
        entry(syscall)

if __name__ == "__main__":
    main()
