
include code/kernel/driver/Makefile
K_SRCS_PATH += \
		code/kernel/boot \
		code/kernel/config \
		code/kernel/driver \
		code/kernel/libs \
		code/kernel/util \
		code/kernel/kernel \
		code/kernel/test \
		code/kernel/mm \
		code/kernel/fs \
		code/kernel/syn \


CFLAGS += \
		-I./code/kernel/boot \
		-I./code/kernel/config \
		-I./code/kernel/driver \
		-I./code/kernel/libs \
		-I./code/kernel/util \
		-I./code/kernel/kernel \
		-I./code/kernel/test \
		-I./code/kernel/mm \
		-I./code/kernel/fs \
		-I./code/kernel/syn \
