
SRCS_PATH += \
		code/kernel/boot \
		code/kernel/config \
		code/kernel/driver \
		code/kernel/libs \
		code/kernel/util \
		code/kernel/kernel \


CFLAGS += \
		-I./code/kernel/boot \
		-I./code/kernel/config \
		-I./code/kernel/driver \
		-I./code/kernel/libs \
		-I./code/kernel/util \
		-I./code/kernel/kernel \
