K_SRCS_PATH += \
		code/kernel/fs/vfs \
		code/kernel/fs/devs \
		code/kernel/fs/pipe \
		code/kernel/fs/sfs \



K_INCLUDE += \
		-I./code/kernel/fs/vfs  \
		-I./code/kernel/fs/devs  \
		-I./code/kernel/fs/pipe  \
		-I./code/kernel/fs/sfs  \
