#!/usr/bin/env python3

# Generate usys.S, the stubs for syscalls.

def main():
    print("# generated by usys.py - do not edit")
    print("#include \"sysdef.h\"")
    print(".section .text")
    def entry(name):
        print(f".global {name}")
        print(f"{name}:")
        print(f" li a7, SYS_{name}")
        print(" ecall")
        print(" ret")

    syscalls = [
        "fork", "exit", "waitpid", "pipe", "read", "write", "close", "kill", "exec",
        "open", "mknod", "unlink", "fstat", "link", "mkdir", "chdir", "dup",
        "getpid", "sbrk", "sleep", "uptime", "sti", "cli", "yield", "gettime",
    ]

    for syscall in syscalls:
        entry(syscall)

if __name__ == "__main__":
    main()
