#ifdef ERROR

ERROR(E_UNSPECIFIED, "Unspecified error")
ERROR(E_BAD_PROC, "Process does not exist")
ERROR(E_INVAL, "Invalid parameter")
ERROR(E_NO_MEM, "Out of memory")
ERROR(E_NO_FREE_PROC, "No available process slot")
ERROR(E_FAULT, "Memory access fault")
ERROR(E_SWAP_FAULT, "Swap I/O error")
ERROR(E_INVAL_ELF, "Invalid ELF file")
ERROR(E_KILLED, "Process was killed")
ERROR(E_PANIC, "Kernel panic")
ERROR(E_TIMEOUT, "Operation timed out")
ERROR(E_TOO_BIG, "Argument too large")
ERROR(E_NO_DEV, "No such device")
ERROR(E_NA_DEV, "Device not available")
ERROR(E_BUSY, "Device or file is busy")
ERROR(E_NOENT, "No such file or directory")
ERROR(E_ISDIR, "Is a directory")
ERROR(E_NOTDIR, "Not a directory")
ERROR(E_XDEV, "Cross-device link")
ERROR(E_UNIMP, "Feature not implemented")
ERROR(E_SEEK, "Illegal seek")
ERROR(E_MAX_OPEN, "Too many open files")
ERROR(E_EXISTS, "File or directory already exists")
ERROR(E_NOTEMPTY, "Directory not empty")
ERROR(E_LOOP, "Symbolic link loop")
ERROR(E_OPEN, "File not open")
ERROR(E_MBX_FULL, "Mailbox is full")
ERROR(E_MBX_EMPTY, "Mailbox is empty")
// net error
ERROR(E_NET, "General network error")
ERROR(E_NET_SIZE, "Packet size too large")
ERROR(E_NET_PARAM, "Invalid network parameter")
ERROR(E_NET_STATE, "Invalid network state")
ERROR(E_NET_MBOX, "Network mailbox error")
ERROR(E_NET_CONFIG, "Network configuration error")
ERROR(E_NET_SYS, "Network system error")
ERROR(E_NET_NONE, "No network resources")
ERROR(E_NET_NOT_SUPPORT, "Feature not supported by network")
ERROR(E_NET_FULL, "Network queue is full")
ERROR(E_NET_DATA, "Network data error")
ERROR(E_NET_MATCH, "Network address mismatch")
ERROR(E_NET_CHECKSUM, "Checksum error")
ERROR(E_NET_EXIST, "Network resource exists")
ERROR(E_NET_CONNECTED, "Already connected")
ERROR(E_NET_UNREACH, "Network unreachable")
ERROR(E_NET_BIND, "Bind error")
ERROR(E_NET_RESET, "Connection reset")
ERROR(E_NET_CLOSE, "Connection closed")
ERROR(E_NET_TMO, "Network timeout")

#endif
